# `php bin/console debug:config api_platform` to see whole configuration

api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    formats:
        json: ['application/json']
        jsonld: ['application/ld+json']
        multipart:
            mime_types: ['multipart/form-data']
    swagger:
        versions: [3]
    collection:
        pagination:
            enabled: true
            items_per_page: 2
