vich_uploader:
    db_driver: orm

    mappings:
        invader_image:
            uri_prefix: /upload/images/invaders
            upload_destination: '%kernel.project_dir%/public/upload/images/invaders'
            namer: App\Vich\Namer\InvaderImageNamer
        city_image:
            uri_prefix: /upload/images/cities
            upload_destination: '%kernel.project_dir%/public/upload/images/cities'
            namer: App\Vich\Namer\CityNamer
