vich_uploader:
    db_driver: orm

    mappings:
        image:
            uri_prefix: /upload/images/invaders
            upload_destination: '%kernel.project_dir%/public/upload/images/invaders'
            namer: App\Vich\Namer\InvaderImageNamer
